# air.toml

# Enables colored output in the console
color = true

# Directories and files to exclude from watching
exclude_list = [
    "tmp",
    "logs",
    ".git",
    "node_modules",
]

# Directories and files to include in the watch list
watch_list = [
    "./*.go",
    "./templates/**/*.html",
    "./static/",
]

# Configuration for running the application
[run]
# Command to run the application
cmd = "go run main.go"
# Enables running the application in a separate shell (optional)
shell = true

# Configuration for killing the running application
[kill]
# Signal to kill the application, e.g., "SIGKILL", "SIGTERM" (optional)
signal = "SIGTERM"
# Delay before sending the kill signal after stopping the run command (optional)
delay = "5s"